version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run backend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Add Environment Variables
          command: |
            eb setenv BCRYPT_PASSWORD=store-password 
            eb setenv ENV=dev 
            eb setenv PORT=3000 
            eb setenv POSTGRES_DB=store 
            eb setenv POSTGRES_HOST=database-2.csjxfdqawy39.us-east-1.rds.amazonaws.com 
            eb setenv POSTGRES_PASSWORD=password123
            eb setenv POSTGRES_TEST_DB=store_test
            eb setenv POSTGRES_USER=full_stack_user
            eb setenv SALT_ROUNDS=10
            eb setenv TOKEN_SECRET=dsfds!5434
      - run:
          name: Deploy App
          command: |
            npm run deploy
            
workflows:
  udagram:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
